custom: 
  service: ${file(env.yml):service}
  provider: ${file(env.yml):provider}
  s3: ${file(env.yml):provider}
  serverless-offline:
    port: 8000

service: ${self:custom.service}

frameworkVersion: ">=1.23.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.provider.region}
  memorySize: 128
  profile: ${self:custom.provider.awsProfile} # aws named profile
  stage: ${opt:stage, 'dev'} # `sls deploy --stage production` if --stage is provided, else use dev
  stackTags: # Optional CF stack tags
    Name: ${self:custom.provider.awsTagName}

functions:
  resize:
    handler: handler.resize
    tags:
      Name: ${self:custom.provider.awsTagName}
    events:
      - http:
          path: '/'
          method: get
          cors: true

plugins:
  - serverless-offline
